"""initial schema

Revision ID: d7420f6fbba6
Revises: 
Create Date: 2026-09-05 22:22:58.022789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7420f6fbba6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DEPARTED', 'CANCELLED', name='flight_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('arrival_time > departure_time', name='ck_flight_time_order'),
    sa.CheckConstraint('origin <> destination', name='ck_flight_distinct_endpoints'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flights_route_departure', 'flights', ['origin', 'destination', 'departure_time'], unique=False)
    op.create_table('passengers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.Enum('PLATINUM', 'GOLD', 'STANDARD', name='passenger_tier'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', 'BUMPED_PENDING', name='booking_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_bookings_passenger_id'), 'bookings', ['passenger_id'], unique=False)
    op.create_table('flight_inventory',
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('physical_capacity', sa.Integer(), nullable=False),
    sa.Column('overbooking_factor', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('booking_limit', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('booked_count >= 0', name='ck_inv_booked_non_negative'),
    sa.CheckConstraint('booking_limit > 0', name='ck_inv_limit_positive'),
    sa.CheckConstraint('overbooking_factor >= 0', name='ck_inv_factor_non_negative'),
    sa.CheckConstraint('physical_capacity > 0', name='ck_inv_capacity_positive'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('booking_legs',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('fare_class', sa.Enum('Y', 'M', 'B', name='fare_class'), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'BUMPED', 'REBOOKED', 'CANCELLED', name='leg_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_leg_sequence_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'sequence', name='uq_leg_booking_sequence')
    )
    op.create_index('ix_legs_flight_status', 'booking_legs', ['flight_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legs_flight_status', table_name='booking_legs')
    op.drop_table('booking_legs')
    op.drop_table('flight_inventory')
    op.drop_index(op.f('ix_bookings_passenger_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('passengers')
    op.drop_index('ix_flights_route_departure', table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###

    # Postgres enum types are standalone objects: DROP TABLE does not remove
    # them, so an un-adjusted downgrade leaves them behind and the next
    # upgrade fails with 'type "flight_status" already exists'.
    for enum_name in (
        "leg_status",
        "fare_class",
        "booking_status",
        "flight_status",
        "passenger_tier",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
